# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9619e4793ab44710001d6ed31055131abb45e63e24d681acfd78a0f814594fef71791070e75eb57e36aabee45a353a6bea55e9cfdbd55f7b7b242aef05df415d

test:
  secret_key_base: 633687016f208d0392b75fe5a1fdd269207b09e974a1bf55249712451a5824d3be5eb560a3faf25c642072bdd0ab000d85c2e481ad33c9bedfe70cab7c8e37ea

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
